/// Flutter icons Ticons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Ticons
///      fonts:
///       - asset: fonts/Ticons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Ticons {
  Ticons._();

  static const _kFontFam = 'Ticons';
  static const String? _kFontPkg = null;

  static const IconData deities = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gallery = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData offering = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData updates = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData about = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
